const tokenKey='et_admin_token';
const state={catalog:[],config:null,team:[]};
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=(v)=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function token(){return localStorage.getItem(tokenKey)||''}
async function api(path,opts={}){const headers={'Content-Type':'application/json'};if(token())headers.Authorization='Bearer '+token();const r=await fetch(path,{...opts,headers});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={error:text}}if(!r.ok)throw new Error(data.error||('请求失败 '+r.status));return data}
function message(text,type='info'){const el=$('#message');el.innerHTML=text?`<div class="toast ${type}" style="position:static;display:block;">${esc(text)}</div>`:''}
const paramLabels={minDeposit:'最低充值金额 (USDT)',minWithdraw:'最低提现金额 (USDT)',minFollowDays:'最低跟单天数',dailySettleHour:'每日结算小时(0-23)',pointsBaseAmount:'积分计算基数金额 (USDT)',pointsPerBase:'每基数获得积分',defaultLanguage:'默认语言 (zh-CN/en/zh-TW)',contactEmail:'联系邮箱',contactTelegram:'Telegram',contactWhatsapp:'WhatsApp'};
const flagLabels={showCrowdfunding:'显示实体众筹',showMall:'显示积分商城',showLeadTrader:'显示我要带单',showInvite:'显示邀请好友',showQuotes:'显示行情专区',showCheckin:'显示每日签到'};
function renderTexts(){const q=($('#textSearch').value||'').trim().toLowerCase();const groups={};for(const item of state.catalog){const hay=(item.category+' '+item.file+' '+item.source).toLowerCase();if(q&&!hay.includes(q))continue;(groups[item.category]||(groups[item.category]=[])).push(item)}let count=0;let html='';for(const [category,items] of Object.entries(groups)){html+=`<div class="cc-group"><h4>${esc(category)} <span style="font-weight:400;color:#94a3b8;font-size:12px;">${items.length} 条</span></h4>`;for(const item of items){count++;const s=item.source;const t=state.config.texts||{};const zh=t['zh-CN']?.[s]||'';const en=t.en?.[s]||'';const tw=t['zh-TW']?.[s]||'';html+=`<div class="cc-row text-item" data-file="${esc(item.file)}"><div class="cc-source">${esc(item.file)} · ${esc(s)}</div><div class="cc-langs"><input data-lang="zh-CN" data-source="${esc(s)}" value="${esc(zh)}" placeholder="留空使用原中文"><input data-lang="en" data-source="${esc(s)}" value="${esc(en)}" placeholder="留空使用内置英文"><input data-lang="zh-TW" data-source="${esc(s)}" value="${esc(tw)}" placeholder="留空使用内置繁体"></div></div>`;}html+='</div>'}if(!html)html='<div class="panel"><div class="panel-body empty">没有匹配的文案</div></div>';$('#textsBox').innerHTML=html;$('#textCount').textContent='显示 '+count+' / '+state.catalog.length+' 条';}
function renderParams(){const known=new Set(Object.keys(paramLabels));const keys=[...known,...Object.keys(state.config.params||{}).filter(k=>!known.has(k))];$('#paramsBox').innerHTML='<div class="form-grid">'+keys.map(k=>`<div class="field cc-param"><label>${esc(paramLabels[k]||k)}</label><input data-param="${esc(k)}" value="${esc(state.config.params?.[k]??'')}"></div>`).join('')+'</div>';}
function renderFlags(){const keys=[...new Set([...Object.keys(flagLabels),...Object.keys(state.config.flags||{})])];$('#flagsBox').innerHTML=keys.map(k=>`<label class="cc-flag"><input type="checkbox" data-flag="${esc(k)}" ${state.config.flags?.[k]!==false?'checked':''}><span>${esc(flagLabels[k]||k)}</span></label>`).join('');}
function renderTeam(){const rows=state.team||[];$('#teamBox').innerHTML=rows.map((m,i)=>`<div class="cc-team-row" data-team-row="${i}"><input data-team-field="name" value="${esc(m.name||'')}" placeholder="姓名"><input data-team-field="level" value="${esc(m.level||m.role||'')}" placeholder="V4/团队长"><input data-team-field="performance" value="${esc(m.performance||m.volume||'')}" placeholder="业绩"><input data-team-field="avatar" value="${esc(m.avatar||'')}" placeholder="头像URL"><input data-team-field="tag" value="${esc(m.tag||'')}" placeholder="标签"><input data-team-field="note" value="${esc(m.note||'')}" placeholder="备注"><button class="btn xs danger" data-remove-team="${i}">删除</button></div>`).join('')||'<div class="empty">暂无静态团队成员</div>';}
function brandingRow(key,label,file=false){const v=state.config.branding?.[key]||'';return `<div class="field"><label>${esc(label)}</label><div class="cc-upload"><input type="text" data-branding="${key}" value="${esc(v)}" placeholder="URL 或文字">${file?`<input type="file" accept="image/*" data-upload-brand="${key}">`:''}</div></div>`}
function renderBranding(){$('#brandingBox').innerHTML='<div class="form-grid">'+brandingRow('app_name','平台名称')+brandingRow('app_slogan','平台标语')+brandingRow('app_logo','平台 LOGO',true)+brandingRow('home_banner_title','首页 Banner 标题')+brandingRow('home_banner_subtitle','首页 Banner 副标题')+brandingRow('home_banner_image','首页 Banner 图片',true)+brandingRow('customer_service','客服提示')+'</div>';}
function collect(){const texts={'zh-CN':{},en:{},'zh-TW':{}};$$('.text-item input[data-source]').forEach(input=>{const v=input.value.trim();if(v)texts[input.dataset.lang][input.dataset.source]=v});const params={};$$('#paramsBox [data-param]').forEach(input=>{const v=input.value.trim();params[input.dataset.param]=v===''?'':(/^-?\d+(\.\d+)?$/.test(v)?Number(v):v)});const flags={};$$('#flagsBox [data-flag]').forEach(input=>flags[input.dataset.flag]=input.checked);const team=$$('#teamBox [data-team-row]').map(row=>{const o={};$$('[data-team-field]',row).forEach(i=>o[i.dataset.teamField]=i.value.trim());return o}).filter(o=>Object.values(o).some(Boolean));const branding={};$$('#brandingBox [data-branding]').forEach(input=>branding[input.dataset.branding]=input.value.trim());return{texts,params,flags,staticTeam:team,branding}}
async function save(){try{message('正在保存...');await api('/api/admin/frontend-config',{method:'PUT',body:JSON.stringify(collect())});message('已保存，前端刷新后生效','success')}catch(e){message(e.message,'error')}}
async function uploadBrand(input){const key=input.dataset.uploadBrand;const file=input.files&&input.files[0];if(!file)return;try{const form=new FormData();form.append('file',file);const r=await fetch('/api/admin/upload',{method:'POST',headers:{Authorization:'Bearer '+token()},body:form});const data=await r.json();if(!r.ok)throw new Error(data.error||'上传失败');$(`[data-branding="${key}"]`).value=data.url;message('上传成功','success')}catch(e){message(e.message,'error')}}
(async()=>{if(!token()){$('#message').innerHTML='<div class="panel"><div class="panel-body">请先登录管理后台：<a href="/admin/">前往登录</a></div></div>';return}try{const [catalog,config]=await Promise.all([api('/api/admin/ui-text-catalog'),api('/api/admin/frontend-config')]);state.catalog=catalog;state.config=config;state.team=config.staticTeam||[];renderTexts();renderParams();renderFlags();renderTeam();renderBranding();}catch(e){message(e.message,'error')}})();
$('#textSearch').addEventListener('input',renderTexts);$('#saveBtn').addEventListener('click',save);$('#addTeamBtn').addEventListener('click',()=>{state.team.push({name:'',level:'',performance:'',avatar:'',tag:'',note:''});renderTeam()});document.addEventListener('change',e=>{if(e.target.matches('[data-upload-brand]'))uploadBrand(e.target)});document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab){$$('.cc-tab').forEach(b=>b.classList.toggle('active',b===tab));$$('.cc-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===tab.dataset.tab))}const del=e.target.closest('[data-remove-team]');if(del){state.team.splice(Number(del.dataset.removeTeam),1);renderTeam()}});
